### ISSUE TITLE
Missing Email Destination on Setting Channel

### ISSUE THREAD

**Issue by yayantritaryana** [ebussola/octobercms-feedback#4]
Hi, 

I'm installed lattest version of this plugin, but i have some problem, email destination setting is missing. i have read on support page from october cms site. it's say this problem fixed on v 1.2.3. but why i still face same problem.
![octobercms](https://cloud.githubusercontent.com/assets/4469391/12079034/7c6807be-b25c-11e5-87a2-2805ef7a04e7.png)

Can you help me ??

Thank's

**Comment by shina** [comment]
Hello! 

Yes, it was fixed.
Could you check for javascript errors on Inspect Element's console?

**Comment by yayantritaryana** [comment]
Thank's for the response.

No error on inspect console, and still missing email destination field

![selection_004](https://cloud.githubusercontent.com/assets/4469391/12092919/a10a1c52-b332-11e5-9c37-d7822cb62c81.png)

**Comment by shina** [comment]
Hey @yayantritaryana, I just did a fresh installation of october and installed the plugin but it works fine.
I tested on Firefox, Chrome and Safari too. But I can't reproduce this problem.

Did you install Feedback from files or form the october marketplace?
Could you try to install it again?
